apiVersion: v1
data:
  my.cnf: |
    [client]
    port=3306
    socket=/tmp/mysql.sock

    [mysqld]
    port=3306
    socket=/tmp/mysql.sock
    key_buffer_size=16M
    max_allowed_packet=128M

    [mysqldump]
    quick
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: configmap-mysql
