apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  replicas: 4
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.6
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-mysql
              key: password
        volumeMounts:
          - name: mysql-vol
            mountPath: /var/lib/mysql
          - name: mysql-conf  
            mountPath: /etc/mysql
      volumes:
      - name: mysql-conf
        configMap:
          name: configmap-mysql  
      - name: mysql-vol
        persistentVolumeClaim:
          claimName: pvc-mysql

